---
# yamllint disable rule:line-length
name: build-image-workflow

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      image_version:
        type: string
        default: 'none'
      label_title:
        required: true
        type: string
      label_description:
        required: true
        type: string
      source_git_ref:
        required: true
        type: string
      timeout_minutes:
        required: true
        type: number
    outputs:
      imageid:
        value: ${{ jobs.build-image.outputs.imageid }}
      digest:
        value: ${{ jobs.build-image.outputs.digest }}
      metadata:
        value: ${{ jobs.build-image.outputs.metadata }}

jobs:
  build-image:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout_minutes }}

    env:
      IMAGE_NAME: ${{ secrets.CONTAINER_REGISTRY }}/${{ vars.CONTAINER_REGISTRY_PATH }}/${{ inputs.image_name }}
      IMAGE_CACHE: ${{ secrets.CONTAINER_REGISTRY }}/${{ vars.CONTAINER_REGISTRY_CACHE_PATH }}/${{ inputs.image_name }}
      PUBLISH: ${{ startsWith(inputs.source_git_ref, 'refs/tags/') && inputs.image_version != 'none' }}

    outputs:
      imageid: ${{ steps.image_info.outputs.imageid }}
      digest: ${{ steps.image_info.outputs.digest }}
      metadata: ${{ steps.image_info.outputs.metadata }}

    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      with:
        fetch-depth: 1
        ref: ${{ inputs.source_git_ref }}

    - name: Set required parameters as environment variables
      shell: bash
      env:
        SOURCE_GIT_REF: ${{ inputs.source_git_ref }}
        CACHE_TO_PARAMS: image-manifest=true,oci-mediatypes=true,mode=max,compression=zstd
      # yamllint disable-line rule:indentation
      run: |
        GIT_SHA="$(git rev-parse --short HEAD)"
        echo "GIT_SHA=$GIT_SHA" >> $GITHUB_ENV

        if [[ "$PUBLISH" == "true" ]]; then
          echo "CACHE_FROM=\"type=registry,ref=${IMAGE_CACHE}:main\"" >> $GITHUB_ENV
          echo "CACHE_TO=\"type=registry,ref=${IMAGE_CACHE}:main,${CACHE_TO_PARAMS}\"" >> $GITHUB_ENV
        else
          CURRENT_BRANCH="$(echo $SOURCE_GIT_REF | cut -d'/' -f3)"
          echo "CURRENT_BRANCH=${CURRENT_BRANCH}" >> $GITHUB_ENV
          echo "CACHE_FROM=\"type=registry,ref=${IMAGE_CACHE}:main,type=registry,ref=${IMAGE_CACHE}:${CURRENT_BRANCH}\"" >> $GITHUB_ENV
          echo "CACHE_TO=\"type=registry,ref=${IMAGE_CACHE}:${CURRENT_BRANCH},${CACHE_TO_PARAMS}\"" >> $GITHUB_ENV
        fi

    - name: Show build parameters
      shell: bash
      run: |
        env | sort | grep -E '^(CACHE_|CURRENT_BRANCH|GIT_SHA|IMAGE_|PUBLISH)'

    - name: Set up QEMU
      uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3
      with:
        buildkitd-flags: '--debug --allow-insecure-entitlement=network.host'
        driver-opts: network=host
        platforms: linux/amd64,linux/arm64

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5
      with:
        images: |
          ${{ env.IMAGE }}
        labels: |
          org.opencontainers.image.title=${{ inputs.label_title }}
          org.opencontainers.image.description=${{ inputs.label_description }}
        tags: |
          type=semver,pattern={{version}},value=${{ inputs.image_version }},enable=${{ env.PUBLISH == 'true' }}
          type=semver,pattern={{major}}.{{minor}},value=${{ inputs.image_version }},enable=${{ env.PUBLISH == 'true' }}
          type=semver,pattern={{major}},value=${{ inputs.image_version }},enable=${{ env.PUBLISH == 'true' }}
          type=raw,value=${{ env.CURRENT_BRANCH }},enable=${{ env.PUBLISH == 'false' }},prefix=branch-
          type=raw,value=${{ env.GIT_SHA }},prefix=git-

    - name: Tailscale Connect
      uses: tailscale/github-action@4e4c49acaa9818630ce0bd7a564372c17e33fb4d # v2
      with:
        oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
        tags: tag:github-action-ci-runner
        # renovate: datasource=github-releases depName=tailscale/tailscale
        version: "1.68.1"

    - name: Login to container registry
      id: login
      uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3
      with:
        registry: ${{ secrets.CONTAINER_REGISTRY }}
        username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

    - name: Build image
      id: build-image
      uses: docker/build-push-action@31159d49c0d4756269a0940a750801a1ea5d7003 # v6
      with:
        context: ./${{ inputs.image_name }}
        platforms: |-
          linux/arm64
          linux/amd64
        load: false
        push: ${{ env.PUBLISH == 'true' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        annotations: ${{ steps.meta.outputs.annotations }}
        cache-from: ${{ env.CACHE_FROM }}
        cache-to: ${{ env.CACHE_TO }}

    - name: Prepare job outputs from image build
      id: image_info
      shell: bash
      env:
        IMAGE_ID: ${{ steps.build-image.outputs.imageid }}
        IMAGE_DIGEST: ${{ steps.build-image.outputs.digest }}
        IMAGE_METADATA: ${{ toJSON(steps.build-image.outputs.metadata) }}
      run: |
        echo "imageid=${IMAGE_ID}" >> $GITHUB_OUTPUT
        echo "digest=${IMAGE_DIGEST}" >> $GITHUB_OUTPUT
        echo "metadata=${IMAGE_METADATA}" >> $GITHUB_OUTPUT

    - name: Load image (non-publish workflow runs only)
      if: ${{ env.PUBLISH == 'false' }}
      uses: docker/build-push-action@31159d49c0d4756269a0940a750801a1ea5d7003 # v6
      with:
        context: ./${{ inputs.image_name }}
        platforms: ${{ (runner.arch == 'ARM64') && 'linux/arm64' || 'linux/amd64' }}
        load: true
        push: false
        tags: ${{ inputs.image_name }}:scan-test
        labels: ${{ steps.meta.outputs.labels }}
        annotations: ${{ steps.meta.outputs.annotations }}
        cache-from: ${{ env.CACHE_FROM }}
        allow: network.host
        network: host

    - name: Run Trivy vulnerability scanner (non-publish workflow runs only)
      if: ${{ env.PUBLISH == 'false' }}
      uses: aquasecurity/trivy-action@0.23.0
      with:
        image-ref: ${{ inputs.image_name }}:scan-test
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'MEDIUM,CRITICAL,HIGH'

    - name: Tailscale Disconnect
      if: success() || failure()
      run: sudo -E tailscale logout
