---
# yamllint disable rule:line-length
name: publish-freeradius-server

# yamllint disable-line rule:truthy
on:
  push:
    branches:
    - main
    paths:
    - freeradius-server/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  publish:
    uses: ./.github/workflows/release-workflow.yaml
    secrets: inherit
    with:
      image_name: freeradius-server
      platforms: linux/amd64,linux/arm64
      source_git_ref: ${{ github.ref }}
