---
# yamllint disable rule:line-length
name: release-workflow

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      platforms:
        required: true
        type: string
      source_git_ref:
        required: true
        type: string
    outputs:
      release_tag:
        value: ${{ jobs.create-release.outputs.release_tag }}

jobs:
  load-image-metadata:
    uses: ./.github/workflows/load-metadata.yaml
    with:
      image_name: ${{ inputs.image_name }}

  create-release:
    needs: [load-image-metadata]
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    outputs:
      release_ref: ${{ steps.release.outputs.release_ref }}
      release_tag: ${{ steps.release.outputs.release_tag }}
      release_timestamp: ${{ steps.release.outputs.release_timestamp }}
    env:
      RELEASE_TAG_PREFIX: ${{ format('{0}/{1}', inputs.image_name, needs.load-image-metadata.outputs.image_version) }}
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        fetch-depth: 0
        fetch-tags: true
        ref: ${{ inputs.source_git_ref }}
    - name: Create release
      id: release
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        IMAGE_NAME: ${{ inputs.image_name }}
      # yamllint disable-line rule:indentation
      run: |
        RELEASE_TIMESTAMP="$(date --utc +%s)"
        RELEASE_TAG="${RELEASE_TAG_PREFIX}-${RELEASE_TIMESTAMP}"
        RELEASE_REF="refs/tags/${RELEASE_TAG}"
        echo "Setting release timestamp to $RELEASE_TIMESTAMP"
        echo "Setting release tag to $RELEASE_TAG"
        echo "Setting release ref to $RELEASE_REF"
        echo
        echo "release_ref=${RELEASE_REF}" >> $GITHUB_OUTPUT
        echo "release_tag=${RELEASE_TAG}" >> $GITHUB_OUTPUT
        echo "release_timestamp=${RELEASE_TIMESTAMP}" >> $GITHUB_OUTPUT
        echo
        echo "Fetching all previous releases..."
        gh api repos/${GITHUB_REPOSITORY}/releases > /tmp/all_releases.json
        cat /tmp/all_releases.json | jq -r '. | sort_by(.published_at) | reverse | .[].tag_name' | pr -t -o 4
        echo
        echo "Filtering down to releases for this image..."
        cat /tmp/all_releases.json | jq -r '. | sort_by(.published_at) | reverse | .[] | select(.tag_name | startswith("'${IMAGE_NAME}'/")) | .tag_name' > /tmp/image_release_tags.list
        cat /tmp/image_release_tags.list | pr -t -o 4
        echo
        echo "Determining previous release for this image..."
        LAST_RELEASE="$(head -1 /tmp/image_release_tags.list)"
        if [[ ! -z "${LAST_RELEASE}" ]]; then
          LAST_RELEASE_SHA=$(git rev-list -n 1 $LAST_RELEASE)
          echo $LAST_RELEASE | pr -t -o 4
          echo $LAST_RELEASE_SHA | pr -t -o 4
          CHANGELOG_RANGE="${LAST_RELEASE_SHA}..main"
        else
          echo "No previous release for ${IMAGE_NAME}." | pr -t -o 4
          CHANGELOG_RANGE="main"
        fi
        echo
        echo "Determining release notes..."
        git log --no-decorate --no-color --no-merges --pretty=format:"- %s" $CHANGELOG_RANGE -- "${IMAGE_NAME}/" > /tmp/release_notes.txt
        cat /tmp/release_notes.txt | pr -t -o 4
        echo
        if (( $(wc -m < /tmp/release_notes.txt) > 0 )); then
          echo "Creating release..."
          gh release create "$RELEASE_TAG" --title "$RELEASE_TAG" --notes-file /tmp/release_notes.txt
          echo "Done."
        else
          echo "No changes since last release."
          echo "Aborting release..."
          exit 1
        fi

  publish:
    needs: [load-image-metadata, create-release]
    uses: ppat/github-workflows/.github/workflows/build-docker-image.yaml@main
    with:
      image_context_path: ${{ inputs.image_name }}
      dockerhub_repository: ppatlabs/${{ inputs.image_name }}
      label_title: ${{ needs.load-image-metadata.outputs.label_title }}
      label_description: ${{ needs.load-image-metadata.outputs.label_description }}
      platforms: ${{ inputs.platforms }}
      private_registry_repository: ${{ vars.CONTAINER_REGISTRY_PATH }}/${{ inputs.image_name }}
      private_registry_build_cache: ${{ vars.CONTAINER_REGISTRY_CACHE_PATH }}/${{ inputs.image_name }}
      source_git_ref: ${{ needs.create-release.outputs.release_ref }}
      timeout_minutes: ${{ fromJSON(needs.load-image-metadata.outputs.build_timeout) }}
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
      private_registry_username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
      private_registry_token: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
      private_registry: ${{ secrets.CONTAINER_REGISTRY }}
      tailscale_oauth_client_id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
      tailscale_oauth_secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
