---
# yamllint disable rule:line-length
name: scan-image

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
    - '.github/workflows/scan-image.yaml'
  schedule:
  - cron: '0 10 */30 * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  scan-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
        - bitwarden-cli
        - freeradius-server
    timeout-minutes: 10

    steps:
    - name: Run Trivy vulnerability scanner (non-publish workflow runs only)
      uses: aquasecurity/trivy-action@7c2007bcb556501da015201bcba5aa14069b74e2 # 0.23.0
      with:
        image-ref: docker.io/ppatlabs/${{ matrix.image }}:latest
        scan-type: image
        format: 'sarif'
        output: 'trivy-results.sarif'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: "MEDIUM,HIGH,CRITICAL"
        scanners: "vuln"

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'
