---
# yamllint disable rule:line-length
name: scan-image

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
    - '.github/workflows/scan-image.yaml'
  schedule:
  - cron: '0 10 */30 * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  scan-image:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
        - bitwarden-cli
        - freeradius-server
    timeout-minutes: 10

    steps:
    - name: Run Trivy vulnerability scanner (non-publish workflow runs only)
      uses: aquasecurity/trivy-action@915b19bbe73b92a6cf82a1bc12b087c9a19a5fe2 # 0.28.0
      with:
        image-ref: docker.io/ppatlabs/${{ matrix.image }}:latest
        scan-type: image
        format: 'sarif'
        output: 'trivy-results.sarif'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: "MEDIUM,HIGH,CRITICAL"
        scanners: "vuln"

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@e2b57b01d64b69ac273abfbea5d3ed15231e1706 # v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'
