---
# yamllint disable rule:line-length
name: test-build-bitwarden-cli

on:
  pull_request:
    paths:
    - 'bitwarden-cli/**'
    - '.github/workflows/test-build-bitwarden-cli.yaml'
    - '.github/workflows/build-image-workflow.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  load-image-metadata:
    uses: ./.github/workflows/load-metadata.yaml
    with:
      image_name: 'bitwarden-cli'

  test-build-bitwarden-cli:
    needs: [load-image-metadata]
    uses: ppat/github-workflows/.github/workflows/build-docker-image.yaml@main
    with:
      image_context_path: bitwarden-cli
      label_title: ${{ needs.load-image-metadata.outputs.label_title }}
      label_description: ${{ needs.load-image-metadata.outputs.label_description }}
      platforms: linux/amd64,linux/arm64
      private_registry_repository: ${{ vars.CONTAINER_REGISTRY_PATH }}/bitwarden-cli
      private_registry_build_cache: ${{ vars.CONTAINER_REGISTRY_CACHE_PATH }}/bitwarden-cli
      source_git_ref: ${{ (github.event_name == 'pull_request') && format('refs/heads/{0}', github.head_ref) || github.ref }}
      timeout_minutes: ${{ fromJSON(needs.load-image-metadata.outputs.build_timeout) }}
    secrets:
      private_registry_username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
      private_registry_token: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
      private_registry: ${{ secrets.CONTAINER_REGISTRY }}
      tailscale_oauth_client_id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
      tailscale_oauth_secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
