---
# yamllint disable rule:line-length
name: test-build-bitwarden-cli

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
    - 'bitwarden-cli/**'
    - '.github/workflows/test-build-bitwarden-cli.yaml'
    - '.github/workflows/build-image-workflow.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  load-image-metadata:
    uses: ./.github/workflows/load-metadata.yaml
    with:
      image_name: 'bitwarden-cli'

  test-build-bitwarden-cli:
    needs: [load-image-metadata]
    uses: ./.github/workflows/build-image-workflow.yaml
    secrets: inherit
    with:
      image_context_path: bitwarden-cli
      label_title: ${{ needs.load-image-metadata.outputs.label_title }}
      label_description: ${{ needs.load-image-metadata.outputs.label_description }}
      repository_private_registry: ${{ secrets.CONTAINER_REGISTRY }}/${{ vars.CONTAINER_REGISTRY_PATH }}/bitwarden-cli
      repository_build_cache: ${{ secrets.CONTAINER_REGISTRY }}/${{ vars.CONTAINER_REGISTRY_CACHE_PATH }}/bitwarden-cli
      source_git_ref: ${{ (github.event_name == 'pull_request') && format('refs/heads/{0}', github.head_ref) || github.ref }}
      timeout_minutes: ${{ fromJSON(needs.load-image-metadata.outputs.build_timeout) }}
