---
# yamllint disable rule:line-length
name: test-build-bitwarden-cli

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
    - 'bitwarden-cli/**'
    - '.github/workflows/test-build-bitwarden-cli.yaml'
    - '.github/workflows/build-image-workflow.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  bust-cache:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.head_ref }}
        fetch-depth: 1
        fetch-tags: false

    - name: show
      shell: bash
      run: |
        echo "Show env"
        echo "--------------------------------------------------------------------------"
        env | sort
        echo "--------------------------------------------------------------------------"
        echo "Show commits"
        git log --oneline --no-merges -1
        echo "--------------------------------------------------------------------------"
        echo "${{toJSON(github.event)}}"
        echo "--------------------------------------------------------------------------"

  load-image-metadata:
    uses: ./.github/workflows/load-metadata.yaml
    with:
      image_name: 'bitwarden-cli'

  test-build-bitwarden-cli:
    needs: [load-image-metadata]
    uses: ./.github/workflows/build-image-workflow.yaml
    secrets: inherit
    with:
      image_name: bitwarden-cli
      label_title: ${{ needs.load-image-metadata.outputs.label_title }}
      label_description: ${{ needs.load-image-metadata.outputs.label_description }}
      source_git_ref: ${{ (github.event_name == 'pull_request') && format('refs/heads/{0}', github.head_ref) || github.ref }}
      timeout_minutes: ${{ fromJSON(needs.load-image-metadata.outputs.build_timeout) }}
