---
# yamllint disable rule:line-length
name: update-aqua-checksum

on:
  pull_request:
    paths:
    - 'tools/aqua.yaml'
    - 'tools/aqua-checksums.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  update-aqua-checksums:
    uses: ppat/github-workflows/.github/workflows/update-aqua-checksums.yaml@b0d4d41a875d2a1a062dc3bebf2907734f6351c6 # v7.0.0
    with:
      git_ref: ${{ github.head_ref || github.ref_name }}
      aqua_dirs: |
        tools
      prune: true
    secrets:
      client_id: ${{ secrets.HOMELAB_BOT_CLIENT_ID }}
      app_private_key: ${{ secrets.HOMELAB_BOT_APP_PRIVATE_KEY }}
